package website.grahamearley.placefinder

/**
 * Data models generated by JsonToKotlinClass: https://github.com/wuseal/JsonToKotlinClass
 */
data class FoursquareResponse(
		val meta: FoursquareResultMetadata,
		val response: Response
)

data class FoursquareResultMetadata(
		val code: Int,
		val requestId: String
)

data class Response(
		val venues: List<Venue>,
		val geocode: Geocode
)

data class Geocode(
		val what: String,
		val where: String,
		val feature: Feature,
		val parents: List<Any>
)

data class Feature(
		val cc: String,
		val name: String,
		val displayName: String,
		val matchedName: String,
		val highlightedName: String,
		val woeType: Int,
		val slug: String,
		val id: String,
		val longId: String,
		val geometry: Geometry
)

data class Geometry(
		val center: Center,
		val bounds: Bounds
)

data class Center(
		val lat: Double,
		val lng: Double
)

data class Bounds(
		val ne: Ne,
		val sw: Sw
)

data class Sw(
		val lat: Double,
		val lng: Double
)

data class Ne(
		val lat: Double,
		val lng: Double
)

data class Venue(
		val id: String,
		val name: String,
		val contact: Contact,
		val location: Location,
		val categories: List<Category>,
		val verified: Boolean,
		val stats: Stats,
		val url: String,
		val hasMenu: Boolean,
		val menu: Menu,
		val allowMenuUrlEdit: Boolean,
		val beenHere: BeenHere,
		val specials: Specials,
		val storeId: String,
		val hereNow: HereNow,
		val referralId: String,
		val venueChains: List<VenueChain>,
		val hasPerk: Boolean
)

data class Category(
		val id: String,
		val name: String,
		val pluralName: String,
		val shortName: String,
		val icon: Icon,
		val primary: Boolean
)

data class Icon(
		val prefix: String,
		val suffix: String
)

data class BeenHere(
		val lastCheckinExpiredAt: Int
)

data class Location(
		val address: String,
		val crossStreet: String,
		val lat: Double,
		val lng: Double,
		val labeledLatLngs: List<LabeledLatLng>,
		val postalCode: String,
		val cc: String,
		val city: String,
		val state: String,
		val country: String,
		val formattedAddress: List<String>
)

data class LabeledLatLng(
		val label: String,
		val lat: Double,
		val lng: Double
)

data class Specials(
		val count: Int,
		val items: List<Any>
)

data class Menu(
		val type: String,
		val label: String,
		val anchor: String,
		val url: String,
		val mobileUrl: String
)

data class HereNow(
		val count: Int,
		val summary: String,
		val groups: List<Any>
)

data class Contact(
		val phone: String,
		val formattedPhone: String,
		val twitter: String,
		val facebook: String,
		val facebookUsername: String,
		val facebookName: String
)

data class Stats(
		val checkinsCount: Int,
		val usersCount: Int,
		val tipCount: Int
)

data class VenueChain(
		val id: String
)